### PR TITLE
Multi-model analysis

### PR DESCRIPTION
**Pull request by jetpack**
Expands Model bias analysis notebook to work on multiple score columns instead of one. In general, all analyses now compute the median and variance across a set of model scores.

I still need to expand this to work on multiple model families in order to see the effect of the experiments, but this is the first step.

Builds on top of the jetpack-cleanup-biasanalysis branch.

Note: the true/false negative term rate plots seem pretty different now compared with before: the plots look less biased. The plots are now based on the median TNRs/FNRs for each term. It's also possible that the models are just better now. Remains to be seen how the experimental models compare with the original model.

### CODE REVIEW

**Comment by nthain** [comment]
Sadly, diff is too large for inline comments. Generally LGTM.

* In cells [88 - 92] you give examples of FP and FN. Why not use the median value for these?

**Comment by jetpack** [comment]
I only added the median score column later on, and didn't go back and fix this. Done.

**Comment by jetpack** [comment]
Uh, dunno how i closed this PR or how to re-open... going to go ahead and merge though.

**Comment by nthain** [comment]
Can you merge a closed PR?

**Comment by jetpack** [comment]
I just merged it manually in git.

**Pull request closed without merging**
